### ISSUE TITLE
add OTs to info page

### ISSUE THREAD

**Issue by KBMD** [jonkb/TicTrainer-node#28]
on home page, change "a “trainer” (e.g. a parent, a psychologist or a physician)" as follows:

a “trainer” (e.g. a parent, a psychologist, an OT or a physician)

same thing on the instructions / how-to page.

**Comment by jonkb** [comment]
Done. Well, I mean that I pushed this change to the master branch.
I can't update the server from here though.
Note: I also reorganized the files a bit, so be careful when restarting the server. The shell scripts that I made to update automatically won't work correctly since they're referencing the old directories.
